# Generated by Django 5.2.1 on 2025-06-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_avertisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avertisement',
            new_name='Advertisement',
        ),
    ]
