# Generated by Django 5.2.1 on 2025-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(help_text='Enter the full address, e.g., 123 News Street, Suite 456, Metropolis, NY 10001, USA', verbose_name='Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('office_hours', models.TextField(help_text='e.g., Mon - Fri: 9:00 AM - 5:00 PM', verbose_name='Office Hours')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
