# Generated by Django 5.2.1 on 2025-07-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_newletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
    ]
