# Generated by Django 5.2.1 on 2025-07-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_rename_newletter_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='update_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
